[build]
target = "index.html"
public_url = "/dev.jerryimmouse"

[[hooks]]
stage = "pre_build"
command = "tailwindcss"
command_arguments = [
    "-i",
    "./input.css",
    "-o",
    "./style/output.css",
    "--minify",
    "--config",
    "./tailwind.config.js",
]
